# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yjqC9AloxGl4Qg7duAP02bx_oii2fqXz
"""

from flask import Flask, request, jsonify
import hashlib
import os

app = Flask(__name__)

# Stable API key (matches your test scripts)
SECRET = b"CHAMELEON_HONEYPOT_SECRET_2024"
VALID_API_KEY = hashlib.sha256(SECRET).hexdigest()

@app.route("/api/honeypot", methods=["POST"])
def honeypot():
    api_key = request.headers.get("x-api-key")
    if api_key != VALID_API_KEY:
        return jsonify({"error": "Invalid API key"}), 401

    data = request.get_json(force=True)

    return jsonify({
        "status": "success",
        "reply": "Oh no… that sounds serious. What should I do?",
        "received": data
    })

@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)