# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-Fimo8o2H4EujMRMX64K0H1kvuEh87A
"""

from flask import Flask, request, jsonify
import hashlib

app = Flask(__name__)

API_KEY = hashlib.sha256(b"CHAMELEON_HONEYPOT_SECRET_2024").hexdigest()

@app.route("/api/honeypot", methods=["POST"])
def honeypot():
    if request.headers.get("x-api-key") != API_KEY:
        return jsonify({"error": "Invalid API key"}), 401

    return jsonify({
        "status": "success",
        "reply": "Honeypot active"
    })

@app.route("/")
def home():
    return "Honeypot API running"

app.run(host="0.0.0.0", port=3000)