# -*- coding: utf-8 -*-
"""requirements.txt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yjqC9AloxGl4Qg7duAP02bx_oii2fqXz
"""

!pip install flask==3.0.2
!pip install gunicorn==21.2.0
!pip install requests==2.31.0